// Generated by IcedCoffeeScript 1.6.2c
(function() {
  var HN;



  HN = (function() {
    function HN() {}

    HN.prototype.subscribe = function(url, tags, period, success_cb, login_cb) {
      var apiurl, data, handler, invocation;
      apiurl = 'http://hasadna-notifications.appspot.com/api/subscribe';
      data = {
        url: url,
        tags: tags,
        period: period
      };
      data = JSON.stringify(data);
      invocation = new XMLHttpRequest();
      handler = function() {
        var response;
        console.log(invocation);
        if (invocation.readyState !== 4) {
          return;
        }
        response = invocation.response;
        console.log(response);
        if (response.success) {
          return success_cb();
        } else {
          url = response.login;
          return login_cb(url);
        }
      };
      if (invocation) {
        invocation.open('POST', apiurl, true);
        invocation.setRequestHeader('Content-Type', 'application/json');
        invocation.responseType = 'json';
        invocation.onreadystatechange = handler;
        invocation.withCredentials = true;
        return invocation.send(data);
      }
    };

    return HN;

  })();

  window.hn = new HN();

}).call(this);
